import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#121212',
        padding: 20,
        paddingTop: 50,
      },
      title: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 20,
        textAlign: 'center',
        color: '#ffffff',
      },
      contentContainer: {
        flex: 1,
        width: '100%',
        marginBottom: 80,
      },
      section: {
        marginBottom: 20,
        padding: 15,
        backgroundColor: '#1E1E1E',
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
      },
      sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
      },
      sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 10,
        color: '#8A2BE2',
      },
      subsectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 5,
        color: '#8A2BE2',
      },
      transcriptText: {
        fontSize: 16,
        color: '#ffffff',
        lineHeight: 24,
      },
      itemText: {
        fontSize: 16,
        color: '#ffffff',
        marginBottom: 8,
        paddingLeft: 10,
        lineHeight: 22,
      },
      itemSubtext: {
        fontSize: 14,
        color: '#888888',
        marginBottom: 4,
        paddingLeft: 20,
      },
      todoItem: {
        marginBottom: 12,
      },
      loadingContainer: {
        position: 'absolute',
        left: 20,
        right: 20,
        bottom: 100,
        alignItems: 'center',
        backgroundColor: '#1E1E1E',
        padding: 20,
        borderRadius: 10,
      },
      loadingText: {
        marginTop: 10,
        color: '#8A2BE2',
        fontSize: 18,
        fontWeight: 'bold',
      },
      bottomButtonContainer: {
        position: 'absolute',
        bottom: 30,
        left: 20,
        right: 20,
        backgroundColor: '#1E1E1E',
        padding: 15,
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: {
          width: 0,
          height: 4,
        },
        shadowOpacity: 0.3,
        shadowRadius: 4.65,
        elevation: 8,
      },
      buttonRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
      },
      mainButton: {
        flex: 0.8,
      },
      cancelButton: {
        flex: 0.18,
        marginLeft: 8,
      },
      recordButton: {
        backgroundColor: '#8A2BE2',
        padding: 12,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
      },
      recordButtonText: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
      },
      emailButton: {
        flex: 0.18,
        marginLeft: 8,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#2A2A2A',
        padding: 10,
        borderRadius: 5,
      },
      modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
      },
      modalContent: {
        backgroundColor: '#1E1E1E',
        padding: 20,
        borderRadius: 10,
        width: '80%',
      },
      modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#ffffff',
        marginBottom: 15,
        textAlign: 'center',
      },
      emailInput: {
        backgroundColor: '#2A2A2A',
        color: '#ffffff',
        padding: 10,
        borderRadius: 5,
        marginBottom: 15,
      },
      editInput: {
        backgroundColor: '#2A2A2A',
        color: '#ffffff',
        padding: 10,
        borderRadius: 5,
        marginBottom: 10,
      },
      editSection: {
        marginBottom: 20,
        padding: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#333',
      },
      editSectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#8A2BE2',
        marginBottom: 10,
      },
      editItem: {
        marginBottom: 15,
        padding: 10,
        backgroundColor: '#252525',
        borderRadius: 5,
      },
      modalButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
      },
      modalButton: {
        flex: 0.48,
        padding: 10,
        borderRadius: 5,
        alignItems: 'center',
      },
      sendButton: {
        backgroundColor: '#8A2BE2',
      },


});

export default styles;
